### ISSUE TITLE
Nuspec in wrong dir

### ISSUE THREAD

**Issue by janusschmidt** [kbilsted/AutoHasher#7]
Hey.
I think the reason that the nuget packaging problem persists, is that your nuget spec file is in the solution dir instead of the project dir. 
Read about it here http://www.appveyor.com/docs/build-phase#packaging-nuget-libraries

**Comment by kbilsted** [comment]
fixed it according to appveyor but nothing to be seen on https://www.nuget.org/packages/AutoHasher/

and no push to sourcesymbols.

Also according to appveyor its publishing v0.1.0 rather than v0.1.0.28 which i would have expected https://ci.appveyor.com/project/kbilsted/autohasher/build/0.1.0.28-rc

**Comment by kbilsted** [comment]
Maybe i should just copy my scripts and roll out manually :)

**Comment by janusschmidt** [comment]
Yeah. That might be easier. :-)
